server:
  port: 8024
spring:
  datasource:
    url: jdbc:mysql://:3306/m_mall_order?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull
    username: dev_client_001
    password: meifute@123
    driver-class-name:  com.mysql.jdbc.Driver
  redis:
    host: 
    port: 6379
    password: meifute@123
  http:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启


eureka-ip: localhost

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${eureka-ip}:8080/eureka/
  instance:
    prefer-ip-address: true

test:
  param: 123456744444fdsfsfs回家开门了，
